version: "3.9"

services:
  # webアプリケーションのコンテナ
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: php82
    volumes:
      - ./src:/var/www
    working_dir: /var/www

  # webサーバーのコンテナ
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./src:/var/www

  # dbサーバーのコンテナ
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-mysql-volume:/var/lib/mysql
volumes:
  db-mysql-volume:
